### ISSUE TITLE
Trips up when there are parameters appended to the URL

### ISSUE THREAD

**Issue by wssrstrm** [davist11/craft-reroute#2]
With a straightforward URL, this plugin works perfectly. So for example:

`/actions/contribute` reroutes to `/forms/-2334271981861470208/contribute` without issue.

However, I have to use a lot of parameters in my URLs for Google Analytics as well as a couple of other tools. So here's what an actual link to the above page might look like:

`/actions/contribute?utm_source=em&utm_medium=html&utm_term=&utm_content=huffpo&utm_campaign=em_20140211_contrib_huffpo&ms=em_20140211_contrib_melanielundquist_huffpo&am=$6`

Would be amazing if the plugin could grab everything before the `?`, find the new URL in the database, append the string starting with the `?` back on, *then* redirect! That would just about save my life.

**Comment by davist11** [comment]
This should be resolved in 1.0.4
