### ISSUE TITLE
CSRF Missing

### ISSUE THREAD

**Issue by cranberry** [davist11/craft-reroute#9]
Once I enabled CSRF in my Craft config this plugin stopped working. Thanks for an otherwise great plugin.

**Comment by thijskaspers** [comment]
True.. This plugin won't work when CSRF is enabled, which I think every Craft website should have enabled.

@davist11 any intention of updating/maintaining this plugin? Also there are some more open issues and pull requests. Thanks in advance

**Comment by davist11** [comment]
Weird, I wasn't getting notifications about PRs. I'll add in the CSRF.
